// BPSC AEDO 2026 — Language Paper Answer Key (English + Hindi)
const langData = [
{q:1,topic:"English Grammar",text:"The news ___ true.",ans:"B — is",exp:"'News' is uncountable singular noun. Always takes singular verb 'is'."},
{q:2,topic:"English Grammar",text:"Introduction of beverages ___ not been without effect.",ans:"B — has",exp:"'Introduction' (singular) + 'has not been'. Present perfect, singular."},
{q:3,topic:"English Grammar",text:"___ he was sleeping, enemy entered.",ans:"C — While",exp:"'While' indicates simultaneous actions. More precise for continuous action."},
{q:4,topic:"English Grammar",text:"I reached ___ the station late.",ans:"B — at",exp:"'Reached' is transitive — no preposition needed. 'Reached the station'. Marked B (at)."},
{q:5,topic:"English Grammar",text:"The alternative ___ submission is death.",ans:"C — for",exp:"'Alternative for' is correct preposition. 'Alternative to' also common."},
{q:6,topic:"English Grammar",text:"I asked ___ a ticket.",ans:"C — for",exp:"'Asked for' = requested. 'Ask for something' is correct phrasal usage."},
{q:7,topic:"English Grammar",text:"He opened box only ___ it empty.",ans:"A — find",exp:"'Only to find' = infinitive of result. Marked A."},
{q:8,topic:"English Grammar",text:"___ my work, I went out to play.",ans:"A — After finishing",exp:"'After finishing' = participial phrase. Correct temporal sequence."},
{q:9,topic:"English Grammar",text:"She qualified ___ a doctor.",ans:"C — to be",exp:"'Qualified to be' = achieved qualification to become."},
{q:10,topic:"English Grammar",text:"Time and Tide ___ for no man.",ans:"A — waits",exp:"'Time and Tide' — compound unit takes singular verb 'waits'. Proverb."},
{q:11,topic:"English Error",text:"Our plane stopped at Mumbai on way to Iran.",ans:"D — No error",exp:"All parts grammatically correct. No error."},
{q:12,topic:"English Error",text:"By next March we shall have been living here for five years.",ans:"D — No error",exp:"'Shall have been living' is correct future perfect continuous. No error."},
{q:13,topic:"English Error",text:"I helped everyone of those girls in doing their home-task.",ans:"B — of those girls in doing",exp:"'Everyone of' should be 'every one of'. Error in part B."},
{q:14,topic:"English Error",text:"To see a crow eating a piece of bread a fox thought...",ans:"B — of bread a fox thought",exp:"Missing comma after 'bread'. Error in punctuation/structure at B."},
{q:15,topic:"English Error",text:"The accident happened due to engine driver's less attention.",ans:"B — due to engine driver's",exp:"'Due to' should be 'owing to' or 'because of'. 'Due to' modifies nouns."},
{q:16,topic:"English Antonym",text:"CORRUPT — antonym",ans:"D — Honest",exp:"Corrupt = dishonest. Antonym = Honest."},
{q:17,topic:"English Antonym",text:"DEVASTATE — antonym",ans:"D — Restore",exp:"Devastate = destroy. Antonym = Restore."},
{q:18,topic:"English Antonym",text:"CONCEAL — antonym",ans:"B — Reveal",exp:"Conceal = hide. Antonym = Reveal."},
{q:19,topic:"English Antonym",text:"DULL — antonym",ans:"C — Bright",exp:"Dull = lacking brightness. Antonym = Bright."},
{q:20,topic:"English Antonym",text:"DEFEAT — antonym",ans:"A — Conquer",exp:"Defeat = to lose. Antonym = Conquer."},
{q:21,topic:"English Synonym",text:"EFFORT — nearest meaning",ans:"B — Attempt",exp:"Effort = try hard. Synonym = Attempt."},
{q:22,topic:"English Synonym",text:"POLITE — nearest meaning",ans:"A — Courteous",exp:"Polite = good manners. Synonym = Courteous."},
{q:23,topic:"English Synonym",text:"GLOOM — nearest meaning",ans:"C — Darkness",exp:"Gloom = partial darkness. Synonym = Darkness."},
{q:24,topic:"English Synonym",text:"LAZY — nearest meaning",ans:"C — Slow",exp:"Lazy = unwilling to work. Nearest = Slow."},
{q:25,topic:"English Synonym",text:"HORROR — nearest meaning",ans:"B — Terror",exp:"Horror = intense fear. Synonym = Terror."},
{q:51,topic:"Hindi Spelling",text:"व्यक्तिक कष्टों — correct spelling",ans:"C — वैयक्तिक",exp:"'Individual' in Hindi = वैयक्तिक (from व्यक्ति + इक)."},
{q:52,topic:"Hindi Spelling",text:"जिजिविषा — correct spelling",ans:"A — जिजीविषा",exp:"जिजीविषा = will to live. Long ई in जी is correct."},
{q:53,topic:"Hindi Spelling",text:"अगरगन्य — correct spelling",ans:"B — अग्रगण्य",exp:"अग्रगण्य = foremost. Correct spelling with conjunct ग्र and ण्य."},
{q:54,topic:"Hindi Spelling",text:"व्यवहारिक — correct spelling",ans:"A — व्यावहारिक",exp:"व्यावहारिक = practical. Long आ after व्य is standard."},
{q:55,topic:"Hindi Spelling",text:"सुवाति — correct spelling",ans:"C — स्वाति",exp:"स्वाति = a nakshatra. The chataka bird thirsts for Swati raindrops."},
{q:56,topic:"Hindi Spelling",text:"अतिश्योक्ति — correct spelling",ans:"A — अतिशयोक्ति",exp:"अतिशयोक्ति = hyperbole (अतिशय + उक्ति)."},
{q:57,topic:"Hindi Spelling",text:"माता-पिता का आर्शीवाद — correct spelling",ans:"D — आशीर्वाद",exp:"आशीर्वाद = blessing (आशीः + वाद). Common spelling error."},
{q:58,topic:"Hindi Spelling",text:"रचयीता — correct spelling",ans:"B — रचयिता",exp:"रचयिता = creator. Short इ not long ई."},
{q:59,topic:"Hindi Spelling",text:"उपयुक्त पंक्तियाँ — correct spelling",ans:"C — उपर्युक्त",exp:"उपर्युक्त = above-mentioned (उपरि + उक्त)."},
{q:60,topic:"Hindi Spelling",text:"प्रादुर्भाव — correct spelling",ans:"D — प्रादुर्भाव",exp:"प्रादुर्भाव = appearance/emergence. This IS correct."},
{q:61,topic:"Hindi Sandhi",text:"महोदय का सही संधि-विच्छेद",ans:"D — महा + उदय",exp:"महोदय: महा + उदय (वृद्धि संधि — आ+उ = ओ)."},
{q:62,topic:"Hindi Sandhi",text:"जगन्नाथ का सही संधि-विच्छेद",ans:"B — जगत् + नाथ",exp:"जगन्नाथ: जगत् + नाथ (व्यंजन संधि — त्+न = न्न)."},
{q:63,topic:"Hindi Sandhi",text:"निश्चल का सही संधि-विच्छेद",ans:"C — निः + चल",exp:"निश्चल: निः + चल (विसर्ग संधि — निः+च = निश्च)."},
{q:64,topic:"Hindi Sandhi",text:"शिखान्त का सही संधि-विच्छेद",ans:"B — शिखा + अन्त",exp:"शिखान्त: शिखा + अन्त (दीर्घ संधि — आ+अ = आ)."},
{q:65,topic:"Hindi Sandhi",text:"वातावरण का सही संधि-विच्छेद",ans:"A — वात + आवरण",exp:"वातावरण: वात + आवरण (दीर्घ संधि — a+ā = ā)."},
{q:66,topic:"Hindi Sandhi",text:"सत्याग्रह का सही संधि-विच्छेद",ans:"B — सत् + आग्रह",exp:"सत्याग्रह: सत् + आग्रह (व्यंजन संधि)."},
{q:67,topic:"Hindi Sandhi",text:"संरक्षक का सही संधि-विच्छेद",ans:"A — सम् + रक्षक",exp:"संरक्षक: सम् + रक्षक (अनुस्वार संधि)."},
{q:68,topic:"Hindi Sandhi",text:"मंत्रिमंडल का सही संधि-विच्छेद",ans:"A — मंत्री + मंडल",exp:"मंत्रिमंडल: मंत्री + मंडल (यण संधि — ई+म = इम)."},
{q:69,topic:"Hindi Sandhi",text:"मनोयोग का सही संधि-विच्छेद",ans:"A — मन: + योग",exp:"मनोयोग: मनः + योग (विसर्ग संधि — अः+य = ओ+य)."},
{q:70,topic:"Hindi Sandhi",text:"गिरीश का सही संधि-विच्छेद",ans:"C — गिरि + ईश",exp:"गिरीश: गिरि + ईश (दीर्घ संधि — इ+ई = ई). Lord of mountains = Shiva."}
];
